#FROM python:3.10-slim
FROM nvidia/cuda:12.4.1-base-ubuntu22.04

RUN apt-get update && apt-get install -y \
    python3.10 \
    python3.10-venv \
    python3.10-dev \
    python3-pip \
    espeak-ng git \
    && rm -rf /var/lib/apt/lists/*

# Set Python 3.10 as the default python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

##########################
RUN pip3 install --upgrade pip
RUN pip3 install -q \
	espeakng==1.0.3 \
	phonemizer==3.3.0 torch==2.6.0 transformers==4.48.2 scipy==1.15.1 munch==4.0.0 \
	kokoro==0.7.9 soundfile==0.13.1 ipython==8.32.0 \
	pypinyin==0.53.0 ordered_set==4.1.0 jieba==0.42.1 cn2an==0.5.23 \
	misaki[ja]==0.7.9 misaki[zh]==0.7.9 misaki[en]==0.7.9

ADD ./warmup.py /warmup.py
RUN python3 /warmup.py

ADD ./generate.py /generate.py

ENTRYPOINT ["python3", "/generate.py"]
