FROM node:20.16.0 as web_compile
WORKDIR /home
RUN git clone https://github.com/kvcache-ai/ktransformers.git
RUN \
	cd ktransformers/ktransformers/website/ && \
	npm install @vue/cli && \
	npm run build && \
	rm -rf node_modules

#FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel as compile_server
FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel as compile_server
WORKDIR /workspace
ENV CUDA_HOME /usr/local/cuda
COPY --from=web_compile /home/ktransformers /workspace/ktransformers
RUN \
apt update -y &&  apt install -y  --no-install-recommends \
    git \
    wget \
    vim \
    gcc \
    g++ \
    cmake && \
    rm -rf /var/lib/apt/lists/*
RUN cd ktransformers && git submodule init && git submodule update
RUN pip install ninja pyproject numpy cpufeature
RUN pip install flash-attn
RUN cd ktransformers && CPU_INSTRUCT=NATIVE  KTRANSFORMERS_FORCE_BUILD=TRUE TORCH_CUDA_ARCH_LIST="8.0;8.6;8.7;8.9;9.0+PTX" pip install . --no-build-isolation --verbose && pip cache purge

ENTRYPOINT ["tail", "-f", "/dev/null"]
